#include "flexspi_boot.h"

#pragma section="app_image"

#pragma location=".conf"
__root const flexspi_nor_config_param_t flexspi_conf = {
  .tag[0] = 'F',            //ascii:F
  .tag[1] = 'C',            //ascii:C
  .tag[2] = 'F',            //ascii:F
  .tag[3] = 'B',            //ascii:B
  .version = FLEXSPI_CFG_VERSION,
#if defined(__FLASH__)
  /*HyperFlash*/
  .readSampleClkSrc = 3,    //3 – Flash provided DQS
  .dataHoldTime =  0,       //Serial Flash CS Hold Time
  .dataSetupTime = 0,       //Serial Flash CS setup time
  .columnAdressWidth = 3,   //3 – For HyperFlash
#else
  /*QSPI Flash*/
  .readSampleClkSrc = 0,    //0 – Dummy Read strobe generated by FlexSPI Controller and loopback internally
  .dataHoldTime =  3,       //Serial Flash CS Hold Time
  .dataSetupTime = 3,       //Serial Flash CS setup time
  .columnAdressWidth = 0,   //3 – For HyperFlash
#endif //__FLASH__
  .deviceModeCfgEnable = 0, //Device Mode Configuration
  .waitTimeCfgCommands = 0, //Wait time for all configuration
                            //commands, unit 100us.
  .deviceModeSeq = 0,       //Sequence parameter for
  .deviceModeArg = 0,       //Device Mode argument
                            //effective only when deviceModeCfgEnable = 1
  .configCmdEnable = 0,     //Config Command Enable feature
  .configCmdSeqs[0] = 0,    //Sequences for Config Command
  .configCmdSeqs[1] = 0,    //Sequences for Config Command
  .configCmdSeqs[2] = 0,    //Sequences for Config Command
  .configCmdSeqs[3] = 0,    //Sequences for Config Command
  .cfgCmdArgs[0] = 0,       //Arguments for Config Command
  .cfgCmdArgs[1] = 0,       //Arguments for configuration command sequence
  .cfgCmdArgs[2] = 0,       //Arguments for configuration command sequence
  .cfgCmdArgs[3] = 0,       //Arguments for configuration command sequence
#if defined(__FLASH__)
  /*HyperFlash*/
  .controllerMiscOption = 0x59,   //
#else
  /*QSPI Flash*/
  .controllerMiscOption = 0x00,   //
#endif //__FLASH__
  .deviceType = 1,          //1 – Serial NOR
#if defined(__FLASH__)
  /*HyperFlash*/
  .sflashPadType = 8,       //8 – Octal pads
  .serialClkFreq = 7,       //7 – 133 MHz
#else
  /*QSPI Flash*/
  .sflashPadType = 4,       //4 – Quad pads
  .serialClkFreq = 3,       //3 – 60 MHz
#endif //__FLASH__
  .lutCustomSeqEnable = 0,  //0 – Use pre-defined LUT sequence index and number
#if defined(__FLASH__)
  /*HyperFlash*/
  .sflashA1Size = 64*1024*1024, //
#else
  /*QSPI Flash*/
  .sflashA1Size = 8*1024*1024, //
#endif //__FLASH__
  .sflashA2Size = 0, //
  .sflashB1Size = 0, //
  .sflashB2Size = 0, //
  .csPadSettingOverride = 0,   //
  .sclkPadSettingOverride = 0, // 
  .dataPadSettingOverride = 0, // 
  .dqsPadSettingOverride = 0,  //  
  .timeoutInMs = 0,            //Maximum wait time during read busy status
  .commandInterval = 0,        //
  .dataValidTime = 0,          //Time from clock edge to data
#if defined(__FLASH__)
  /*HyperFlash*/
  .busyOffset = 15,            //busy bit offset, valid range : 0-31
  .busyBitPolarity = 1,        //1 – busy bit is 0 if device is busy
#else
  /*QSPI Flash*/
  .busyOffset = 0,             //busy bit offset, valid range : 0-31
  .busyBitPolarity = 0,        //1 – busy bit is 0 if device is busy
#endif //__FLASH__
#if defined(__FLASH__)
  /*HyperFlash*/
  /*Read Command*/
  .lookupTable[(0<<3)+0] = FLEXSPI_LUT_INST(LUT_CODE_CMD_DDR,   LUT_PADS_EIGHT,   0xA0),
  .lookupTable[(0<<3)+1] = FLEXSPI_LUT_INST(LUT_CODE_RADDR_DDR, LUT_PADS_EIGHT,   0x18),
  .lookupTable[(0<<3)+2] = FLEXSPI_LUT_INST(LUT_CODE_CADDR_DDR, LUT_PADS_EIGHT,   0x10),
  .lookupTable[(0<<3)+3] = FLEXSPI_LUT_INST(LUT_CODE_READ_DDR,  LUT_PADS_EIGHT,   0x04),
  .lookupTable[(0<<3)+4] = FLEXSPI_LUT_INST(LUT_CODE_STOP,      0,                   0),
#else
  /*QSPI Flash*/
  /*Read Command*/
  .lookupTable[(0<<3)+0] = FLEXSPI_LUT_INST(LUT_CODE_CMD_SDR,    LUT_PADS_ONE,  0x0B),
  .lookupTable[(0<<3)+1] = FLEXSPI_LUT_INST(LUT_CODE_RADDR_SDR,  LUT_PADS_ONE,  0x18),
  .lookupTable[(0<<3)+2] = FLEXSPI_LUT_INST(LUT_CODE_DUMMY_SDR,  LUT_PADS_ONE,     8),
  .lookupTable[(0<<3)+3] = FLEXSPI_LUT_INST(LUT_CODE_READ_SDR,   LUT_PADS_ONE,     8),
  .lookupTable[(0<<3)+4] = FLEXSPI_LUT_INST(LUT_CODE_JMP_ON_CS,  0,                0),
#endif //__FLASH__

  //lutCustomSeq[48] = ;       //  
#if defined(__FLASH__)
  /*HyperFlash*/
  .pageSize = 512,             //Page size in terms of bytes,not used by ROM
  .sectorSize = 256*1024,     //Sector size in terms of bytes,not used by ROM
  .ipCmdSerialClkFreq = 7,    //Chip specific value, not used by ROM
#else
  /*QSPI Flash*/
  .pageSize = 256,              //Page size in terms of bytes,not used by ROM
  .sectorSize = 32*1024,       //Sector size in terms of bytes,not used by ROM
  .ipCmdSerialClkFreq = 3,    //Chip specific value, not used by ROM
#endif //__FLASH__
 };

#pragma location=".ivt"
__root const ivt image_vector_table = {
  IVT_HEADER,                         /* IVT Header */
  (uint32_t)__iar_program_start,      /* Image  Entry Function */
  IVT_RSVD,                           /* Reserved = 0 */
  NULL,                               /* Address where DCD information is stored */
  (uint32_t)&boot_data,               /* Address where BOOT Data Structure is stored */
  (uint32_t)&image_vector_table,      /* Pointer to IVT Self (absolute address */
  (uint32_t)0,                        /* Address where CSF file is stored */
  IVT_RSVD,
};

#pragma location=".ivt"
const boot_data_t boot_data = {
  __section_begin("app_image"),
  __section_size("app_image"),      /* size */
  0,                                /* Plugin flag*/
  0xFFFFFFFF                        /* empty - extra data word */
};
