
/*
*****************************************************************************
**
**      Project     : My project
**
**      Component   : LPC2106 (LPC2106)
**
**      Modulename  : System
**
**      Filename    : template.c
**
**      Abstract    : This file is the template file for an application
**                    Rename the file from <template.c> to e.g. <usercode.c>
**                    The file contains an example of main function
**
**                    Modify the <usercode.c> to suit your application.
**                    The <usercode.c> file will not be overwritten by MakeApp.
**
**      Date        : 2004-05-26 17:21:26
**
**      License no. : 9503-663-863-6224     Ivan
**
**      Warning     : This file has been automatically generated.
**                    Do not edit this file if you intend to regenerate it.
**
**      This template file was created by IAR MakeApp version 
**      4.02A (NXP LPC210x: 4.00C) for the NXP LPC210X series of
**      microcontrollers.
**
**      (c)Copyright 2004 IAR Systems.
**      Your rights to this file are explained in the IAR MakeApp 
**      License Agreement. All other rights reserved.
**
*****************************************************************************
*/
/*
**===========================================================================
**  1       GENERAL
**  1.1     Revisions
**
**  Please read the IAR MakeApp for NXP LPC210x readme file 
**  
**
**===========================================================================
*/

/*
**===========================================================================
**  1.2     References
** 
**  No   Identification          Name or Description
**  ==   ===================     ================================
**
**  1    02/Oct/2003             NXP LPC210x Hardware Manual
** 
**===========================================================================
*/

/*
**===========================================================================
**  2.      INCLUDE FILES
**  2.1     Standard include files
**===========================================================================
*/

/*
**===========================================================================
**  2.2     Application include files
**===========================================================================
*/

#include "usercode.h"   /* Usercode macros (see <template.h>) */
#include "ma_tgt.h"     /* Target specific header file */
#include "ma_sfr.h"     /* Special function register bitfield macros */
#include "iolpc210x.h"  /* Defines Special function registers */

/*
**---------------------------------------------------
**  IAR MakeApp peripheral modules header files 
**  Include the header files used by the application
**---------------------------------------------------
*/
#include "ma_scb.h"
#include "ma_vic.h"
#include "ma_pcb.h"
#include "ma_gpio.h"
#include "ma_uart0.h"
#include "ma_uart1.h"
#include "ma_i2c.h"
#include "ma_spi.h"
#include "ma_tmr.h"
#include "ma_pwm0.h"
#include "ma_rtc.h"
#include "ma_wdt.h"


/*
**===========================================================================
**  3.      DECLARATIONS
**  3.1     Internal constants
**===========================================================================
*/



/*
**===========================================================================
**  3.2     Internal macros
**===========================================================================
*/

/*
**===========================================================================
**  3.3     Internal type definitions
**===========================================================================
*/

/*
**===========================================================================
**  3.4     Global variables (declared as 'extern' in some header file)
**===========================================================================
*/

/*
**===========================================================================
**  3.5     Internal function prototypes (defined in Section 5)
**===========================================================================
*/

/*
**===========================================================================
**  3.6     Internal variables
**===========================================================================
*/

/*
**===========================================================================
**  4.      GLOBAL FUNCTIONS (declared as 'extern' in some header file)
**===========================================================================
*/



void main( void ) 
/*
**---------------------------------------------------------------------------
**
**  Abstract:
**      User application
**
**  Parameters:
**      None
**
**  Returns:
**      None
**
**---------------------------------------------------------------------------
*/
{
    /*
    **------------------------------------------------------------------
    ** System init
    **------------------------------------------------------------------
    */
    MA_Init_SCB();

    /*
    **-----------------------------
    ** Initialise used peripherals 
    **-----------------------------
    */
/*
    MA_Init_VIC();
    MA_Init_PCB();
    MA_Init_GPIO();
    MA_Init_UART0();
    MA_Init_UART1();
    MA_Init_I2C();    
    MA_Init_SPI();
    MA_Init_TIMER();
    MA_Init_PWM0();
    MA_Init_RTC();
    MA_Init_WDT();    
*/

    /*
    **--------------------------------------------
    ** Initialise used interrupt service routines
    **--------------------------------------------
    */
    /* MA_SetISRAddress_VIC((U8 *)&MA_IntHandler_UART1, 5); */
    
        
    /*
    **---------------------------------
    ** Your application code goes here
    **---------------------------------
    */
    while( 1 )
    {
        
    }

} /* main */


/*
**===========================================================================
**  5.      INTERNAL FUNCTIONS (declared in Section 3.5)
**===========================================================================
*/

/*
**===========================================================================
** END OF FILE
**===========================================================================
*/ 


