/**********************************************************************
* $Id: sct_fsm.c 28 2014-01-27 14:45:13Z danielru $		sct_fsm.c			2011-06-02
*//**
* @file		sct_fsm.c
* @brief	This file contains function initialize SCT FSM module
* @version	1.0
* @date		02. June. 2011
* @author	NXP MCU SW Application Team
*
* Copyright(C) 2011, NXP Semiconductor
* All rights reserved.
*
***********************************************************************
* Software that is described herein is for illustrative purposes only
* which provides customers with programming information regarding the
* products. This software is supplied "AS IS" without any warranties.
* NXP Semiconductors assumes no responsibility or liability for the
* use of the software, conveys no license or title under any patent,
* copyright, or mask work right to the product. NXP Semiconductors
* reserves the right to make changes in the software without
* notification. NXP Semiconductors also make no representation or
* warranty that such application will be suitable for the specified
* use without further testing or modification.
**********************************************************************/
/* Generated by fzmparser version 1.14 --- DO NOT EDIT! */

/* Uses following resources: */
/* [4 events, 4+0 states, 1 inputs, 1 outputs, 1 match regs, 4 capture regs] */

#include "sct_fsm.h"


void sct_fsm_init (void)
{
	/* MATCH/CAPTURE registers */
	LPC_SCT->REGMODE_L = 0x001E;         /* L: 1x MATCH, 4x CAPTURE, 11 unused */
	LPC_SCT->REGMODE_H = 0x0000;             /* H: 0x MATCH, 0x CAPTURE, 16 unused */
	LPC_SCT->MATCH_L[0] = timeout;
	LPC_SCT->MATCHREL_L[0] = timeout;
	LPC_SCT->CAPCTRL_L[1] = 0x0001;
	LPC_SCT->CAPCTRL_L[2] = 0x0004;
	LPC_SCT->CAPCTRL_L[3] = 0x0002;
	LPC_SCT->CAPCTRL_L[4] = 0x0008;

	/* OUTPUT registers */
	LPC_SCT->OUT[0].SET = 0x0000000F;        /* DONE */
	LPC_SCT->OUT[0].CLR = 0x0000000F;
	  /* Unused outputs must not be affected by any event */
	LPC_SCT->OUT[1].SET = 0;
	LPC_SCT->OUT[1].CLR = 0;
	LPC_SCT->OUT[2].SET = 0;
	LPC_SCT->OUT[2].CLR = 0;
	LPC_SCT->OUT[3].SET = 0;
	LPC_SCT->OUT[3].CLR = 0;
	LPC_SCT->OUT[4].SET = 0;
	LPC_SCT->OUT[4].CLR = 0;
	LPC_SCT->OUT[5].SET = 0;
	LPC_SCT->OUT[5].CLR = 0;
	LPC_SCT->OUT[6].SET = 0;
	LPC_SCT->OUT[6].CLR = 0;
	LPC_SCT->OUT[7].SET = 0;
	LPC_SCT->OUT[7].CLR = 0;
	LPC_SCT->OUT[8].SET = 0;
	LPC_SCT->OUT[8].CLR = 0;
	LPC_SCT->OUT[9].SET = 0;
	LPC_SCT->OUT[9].CLR = 0;
	LPC_SCT->OUT[10].SET = 0;
	LPC_SCT->OUT[10].CLR = 0;
	LPC_SCT->OUT[11].SET = 0;
	LPC_SCT->OUT[11].CLR = 0;
	LPC_SCT->OUT[12].SET = 0;
	LPC_SCT->OUT[12].CLR = 0;
	LPC_SCT->OUT[13].SET = 0;
	LPC_SCT->OUT[13].CLR = 0;
	LPC_SCT->OUT[14].SET = 0;
	LPC_SCT->OUT[14].CLR = 0;
	LPC_SCT->OUT[15].SET = 0;
	LPC_SCT->OUT[15].CLR = 0;
	LPC_SCT->OUTPUT = (LPC_SCT->OUTPUT & ~0x00000001) | 0x00000000;

	/* Conflict resolution register */
	LPC_SCT->RES = (LPC_SCT->RES & ~0x00000003) | 0x00000003;

	/* EVENT registers */
	LPC_SCT->EVENT[0].CTRL = 0x00006880;     /* L: --> state CAP2 */
	LPC_SCT->EVENT[0].STATE = 0x00000008;
	LPC_SCT->EVENT[1].CTRL = 0x00016880;     /* L: --> state CAP3 */
	LPC_SCT->EVENT[1].STATE = 0x00000001;
	LPC_SCT->EVENT[2].CTRL = 0x0000E880;     /* L: --> state L_ENTRY */
	LPC_SCT->EVENT[2].STATE = 0x00000004;
	LPC_SCT->EVENT[3].CTRL = 0x0001E880;     /* L: --> state CAP1 */
	LPC_SCT->EVENT[3].STATE = 0x00000002;
	  /* Unused events must not have any effect */
	LPC_SCT->EVENT[4].STATE = 0;
	LPC_SCT->EVENT[5].STATE = 0;
	LPC_SCT->EVENT[6].STATE = 0;
	LPC_SCT->EVENT[7].STATE = 0;
	LPC_SCT->EVENT[8].STATE = 0;
	LPC_SCT->EVENT[9].STATE = 0;
	LPC_SCT->EVENT[10].STATE = 0;
	LPC_SCT->EVENT[11].STATE = 0;
	LPC_SCT->EVENT[12].STATE = 0;
	LPC_SCT->EVENT[13].STATE = 0;
	LPC_SCT->EVENT[14].STATE = 0;
	LPC_SCT->EVENT[15].STATE = 0;

	/* STATE registers */
	LPC_SCT->STATE_L = 1;
	LPC_SCT->STATE_H = 0; /* implicit value */

	/* state names assignment: */
	  /* State L 0: CAP2 */
	  /* State L 1: L_ENTRY */
	  /* State L 2: CAP3 */
	  /* State L 3: CAP1 */

	/* CORE registers */
	LPC_SCT->START_L = 0x0000;
	LPC_SCT->STOP_L =  0x0004;
	LPC_SCT->HALT_L =  0x0000;
	LPC_SCT->LIMIT_L = 0x0004;
	LPC_SCT->START_H = 0x0000;
	LPC_SCT->STOP_H =  0x0000;
	LPC_SCT->HALT_H =  0x0000;
	LPC_SCT->LIMIT_H = 0x0000;
	LPC_SCT->EVEN =    0x00000004;
	LPC_SCT->DMA0REQUEST = 0x00000000;
	LPC_SCT->DMA1REQUEST = 0x00000000;

}
