/**********************************************************************
* $Id: sct_fsm.h 28 2014-01-27 14:45:13Z danielru $		sct_fsm.h			2011-06-02
*//**
* @file		sct_fsm.h
* @brief	Contains all macro definitions and function prototypes
* 			support for initialize SCT FSM module
* @version	1.0
* @date		02. June. 2011
* @author	NXP MCU SW Application Team
*
* Copyright(C) 2011, NXP Semiconductor
* All rights reserved.
*
***********************************************************************
* Software that is described herein is for illustrative purposes only
* which provides customers with programming information regarding the
* products. This software is supplied "AS IS" without any warranties.
* NXP Semiconductors assumes no responsibility or liability for the
* use of the software, conveys no license or title under any patent,
* copyright, or mask work right to the product. NXP Semiconductors
* reserves the right to make changes in the software without
* notification. NXP Semiconductors also make no representation or
* warranty that such application will be suitable for the specified
* use without further testing or modification.
**********************************************************************/
#ifndef __SCT_FSM_H__
#define __SCT_FSM_H__

/* Generated by fzmparser version 1.14 --- DO NOT EDIT! */

#include "sct_user.h"

extern void sct_fsm_init(void);

/* macros for defining the mapping between IRQ and events */
#define SCT_IRQ_EVENT_capture_complete (2)

/* Input assignments */
#define SCT_INPUT_IN (2)

/* Output assignments (and their defaults if specified) */
#define SCT_OUTPUT_DONE (0)
#define SCT_OUTPUTPRELOAD_DONE (0)

/* Capture registers */
#define SCT_CAPTURE_sample2 LPC_SCT->CAP_L[1]
#define SCT_CAPTURE_sample4 LPC_SCT->CAP_L[2]
#define SCT_CAPTURE_sample3 LPC_SCT->CAP_L[3]
#define SCT_CAPTURE_sample1 LPC_SCT->CAP_L[4]


/* Match register reload macro definitions */
#define reload_count(value) LPC_SCT->MATCHREL_L[0] = value;

#endif
