/*
 * Copyright (c) 2010 Freescale Semiconductor;
 * All Rights Reserved
 *
 * THIS SOFTWARE IS PROVIDED BY FREESCALE "AS IS" AND ANY EXPRESSED OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL FREESCALE OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
 * IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef _BSP_K64_H_
#define _BSP_K64_H_

#include "common.h"
#include "Settings.h"

enum usb_clock {
	MCGPLL0,
	MCGFLL,
	CLKIN
};

/* Select Clock source */
#define USB_CLOCK			MCGPLL0
//#define USB_CLOCK			MCGFLL
//#define USB_CLOCK			CLKIN

/* USB Fractional Divider value for 96MHz input */
/* USB Clock = PLL x (FRAC +1) / (DIV+1) */
/* USB Clock = 120MHz x (1+1) / (4+1) = 48 MHz */

#define USB_FRAC			1
#define USB_DIV				SIM_CLKDIV2_USBDIV(4)

#define FLAG_SET(BitNumber, Register)		(Register |=(1<<BitNumber))
#define FLAG_CLR(BitNumber, Register)		(Register &=~(1<<BitNumber))
#define FLAG_CHK(BitNumber, Register)		(Register & (1<<BitNumber))

#define ENABLE_USB_5V		GPIOC_PSOR|=(1<<9);
#define DISABLE_USB_5V		GPIOC_PCOR|=(1<<9);

void vfnInitUSBClock(uint8 u8ClkOption);

#endif		/* _BSP_K64_H_ */
